### ISSUE TITLE
Upgrading coguard-cli | pip version issue

### ISSUE THREAD

**Issue by julianm-lrj** [coguardio/coguard-cli#37]
user:
non-root

coguard-cli
current version : 0.1.14
target version : 0.1.17

pip 
current version : 22.2.1

Issue:  
using env config upgrading coguard-cli resulted with output:

--- cli output ---

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: coguard-cli in /home/julianm/.local/lib/python3.8/site-packages (0.1.14)
Collecting coguard-cli
  Downloading coguard_cli-0.1.17-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.8/69.8 kB 823.5 kB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from coguard-cli) (45.2.0)
Requirement already satisfied: requests in /home/julianm/.local/lib/python3.8/site-packages (from coguard-cli) (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->coguard-cli) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->coguard-cli) (2019.11.28)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/julianm/.local/lib/python3.8/site-packages (from requests->coguard-cli) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->coguard-cli) (1.25.8)
Installing collected packages: coguard-cli
  Attempting uninstall: coguard-cli
    Found existing installation: coguard-cli 0.1.14
    Uninstalling coguard-cli-0.1.14:
      Successfully uninstalled coguard-cli-0.1.14
Successfully installed coguard-cli-0.1.17
--- Logging error ---
Traceback (most recent call last):
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1673, in print
    extend(render(renderable, render_options))
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1305, in render
    for render_output in iter_render:
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
    for segment in segments:
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1283, in render
    renderable = rich_cast(renderable)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
Call stack:
  File "/home/julianm/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
    logger.warning("[present-rich] %s", upgrade_prompt)
  File "/usr/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/julianm/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2.1', new='22.2.2'),)

resolution:
manual upgrade pip to 22.2.2

**Comment by ioah86** [comment]
Thank you, I will have a look
